"""init

Revision ID: 427c30065f29
Revises: e977a182ec00
Create Date: 2025-12-30 19:50:11.869257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '427c30065f29'
down_revision: Union[str, Sequence[str], None] = 'e977a182ec00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clientes', 'alias',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.drop_constraint(op.f('direcciones_cliente_id_fkey'), 'direcciones', type_='foreignkey')
    op.create_foreign_key(None, 'direcciones', 'clientes', ['cliente_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('pedidos_direccion_id_fkey'), 'pedidos', type_='foreignkey')
    op.drop_constraint(op.f('pedidos_cliente_id_fkey'), 'pedidos', type_='foreignkey')
    op.create_foreign_key(None, 'pedidos', 'direcciones', ['direccion_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pedidos', 'clientes', ['cliente_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.create_foreign_key(op.f('pedidos_cliente_id_fkey'), 'pedidos', 'clientes', ['cliente_id'], ['id'])
    op.create_foreign_key(op.f('pedidos_direccion_id_fkey'), 'pedidos', 'direcciones', ['direccion_id'], ['id'])
    op.drop_constraint(None, 'direcciones', type_='foreignkey')
    op.create_foreign_key(op.f('direcciones_cliente_id_fkey'), 'direcciones', 'clientes', ['cliente_id'], ['id'])
    op.alter_column('clientes', 'alias',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
