"""init schema

Revision ID: d5015bf2df00
Revises: 
Create Date: 2025-12-26 16:40:18.338958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5015bf2df00'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_cliente', sa.String(length=50), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_codigo_cliente'), 'clientes', ['codigo_cliente'], unique=True)
    op.create_index(op.f('ix_clientes_telefono'), 'clientes', ['telefono'], unique=False)
    op.create_table('direcciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('texto_original', sa.String(length=300), nullable=False),
    sa.Column('distrito', sa.String(length=80), nullable=True),
    sa.Column('referencia', sa.String(length=120), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direcciones_cliente_id'), 'direcciones', ['cliente_id'], unique=False)
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('direccion_id', sa.Integer(), nullable=False),
    sa.Column('fecha_pedido', sa.Date(), nullable=False),
    sa.Column('cantidad_balones', sa.Integer(), nullable=False),
    sa.Column('total_soles', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pagado', sa.Boolean(), nullable=False),
    sa.Column('saldo_pendiente', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['direccion_id'], ['direcciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_cliente_id'), 'pedidos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_pedidos_direccion_id'), 'pedidos', ['direccion_id'], unique=False)
    op.create_index(op.f('ix_pedidos_fecha_pedido'), 'pedidos', ['fecha_pedido'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedidos_fecha_pedido'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_direccion_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_cliente_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_direcciones_cliente_id'), table_name='direcciones')
    op.drop_table('direcciones')
    op.drop_index(op.f('ix_clientes_telefono'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_codigo_cliente'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
